### main  page
GET http://localhost:3000/

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "appp5@aapp5.com",
    "password": "123456"
}

### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "jam@bond",
    "password": "123456"
}

### GET all items
GET http://localhost:3000/api/items

### GET single
GET http://localhost:3000/api/items/3

### POST item
POST http://localhost:3000/api/items/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmRAY29tIiwic3ViIjoxLCJpYXQiOjE3MDU1OTY1MzksImV4cCI6MTcwNTYwMDEzOX0.ThZuxSKRQaUuvnUhWw4IVAsum-rRZ0_i-6hrSeyWmU8

{
    "title": "Cup",
    "description": "Blue, ceramic",
    "price": 2.50,
    "rating": 3.98,
    "stock": 60,
    "cat_id": 7,
    "img_url": "https://picsum.photos/id/4/800/600"
}

### DELETE single item
DELETE  http://localhost:3000/api/items/2

### GET all categories
GET  http://localhost:3000/api/categories

### GET all orders
GET  http://localhost:3000/api/orders

### GET single users order
GET  http://localhost:3000/api/orders/user/1

### POST create users order
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "id": 1,
  "item_id": 1,
  "customer_id": 1,
  "qty": 1,
  "total": 500
}

### PUT update categories
PUT http://localhost:3000/api/categories/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwcHA1QGFhcHA1LmNvbSIsInVzZXJJZCI6Niwic2NvcGUiOiJjdXN0b21lciIsImlhdCI6MTcwNzMwNDIwMSwiZXhwIjoxNzA3MzA3ODAxfQ.uY25X6qjs21OawH7zWK1SledvS5h8A6SVDQqWQbFzLM

{
    "name": "Books"
}